name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: pnpm/action-setup@f2b2b233b538f500472c7274c7012f57857d8ce0
        with:
          with_install: false
      - uses: actions/setup-node@d7a11313b581b306c961b506cfc8971208bb03f6
        with:
          node-version: 24
      - run: pnpm install --frozen-lockfile
      - run: pnpm run format:check

  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: pnpm/action-setup@f2b2b233b538f500472c7274c7012f57857d8ce0
        with:
          with_install: false
      - uses: actions/setup-node@d7a11313b581b306c961b506cfc8971208bb03f6
        with:
          node-version: 24
      - run: pnpm install --frozen-lockfile
      - run: pnpm test --browsers=ChromeHeadless --watch=false
